# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
addons:
  apt:
    update: true
env:
  - PACKAGE_NAME=pytest-emoji-output PACKAGE_VERSION=0.1.8
before_install:
  - sudo add-apt-repository -y ppa:duggan/bats
  - sudo apt-get -y install bats
install:
  - pip install pip -U
  - pip install -r requirements-dev.txt -U
script:
    - ./analyse-code.sh
    - ./test-package.sh
after_success:
  - coveralls
notifications:
  email: false